"""J1939 PGN and SPN database.

Pure data module containing definitions for known Parameter Group Numbers (PGNs)
and Suspect Parameter Numbers (SPNs). Extend this file to add support for
additional J1939 parameters.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class SPNDefinition:
    """Definition of a single J1939 Suspect Parameter Number."""

    spn: int
    name: str
    pgn: int
    start_byte: int  # 1-indexed byte position in CAN data payload
    start_bit: int  # 1-indexed bit within start byte (1=LSB, 8=MSB)
    bit_length: int  # Total number of bits
    resolution: float  # physical = raw * resolution + offset
    offset: float
    unit: str
    min_value: float | None = None
    max_value: float | None = None
    states: dict[int, str] | None = None


@dataclass(frozen=True, slots=True)
class PGNDefinition:
    """Definition of a J1939 Parameter Group Number."""

    pgn: int
    name: str
    acronym: str
    length: int  # Data length in bytes (typically 8)
    spns: tuple[int, ...]  # SPN numbers contained in this PGN


# ---------------------------------------------------------------------------
# PGN Database
# ---------------------------------------------------------------------------

PGN_DATABASE: dict[int, PGNDefinition] = {
    # PGN 61444 - Electronic Engine Controller 1
    61444: PGNDefinition(
        pgn=61444,
        name="Electronic Engine Controller 1",
        acronym="EEC1",
        length=8,
        spns=(899, 512, 513, 190, 1483, 2432),
    ),
    # PGN 61443 - Electronic Engine Controller 2
    61443: PGNDefinition(
        pgn=61443,
        name="Electronic Engine Controller 2",
        acronym="EEC2",
        length=8,
        spns=(29, 91, 92, 974, 2970),
    ),
    # PGN 65262 - Engine Temperature 1
    65262: PGNDefinition(
        pgn=65262,
        name="Engine Temperature 1",
        acronym="ET1",
        length=8,
        spns=(110, 174, 175, 176, 52, 1134),
    ),
    # PGN 65188 - Engine Temperature 2
    65188: PGNDefinition(
        pgn=65188,
        name="Engine Temperature 2",
        acronym="ET2",
        length=8,
        spns=(1135, 1136, 411, 412),
    ),
    # PGN 65263 - Engine Fluid Level/Pressure 1
    65263: PGNDefinition(
        pgn=65263,
        name="Engine Fluid Level/Pressure 1",
        acronym="EFL/P1",
        length=8,
        spns=(94, 22, 98, 100, 101, 109, 111),
    ),
    # PGN 65243 - Engine Fluid Level/Pressure 2
    65243: PGNDefinition(
        pgn=65243,
        name="Engine Fluid Level/Pressure 2",
        acronym="EFL/P2",
        length=8,
        spns=(164, 157, 156, 1349),
    ),
    # PGN 65265 - Cruise Control/Vehicle Speed 1
    65265: PGNDefinition(
        pgn=65265,
        name="Cruise Control/Vehicle Speed 1",
        acronym="CCVS1",
        length=8,
        spns=(70, 84, 595, 596, 597, 598, 86),
    ),
    # PGN 65253 - Engine Hours, Revolutions
    65253: PGNDefinition(
        pgn=65253,
        name="Engine Hours, Revolutions",
        acronym="HOURS",
        length=8,
        spns=(247, 249),
    ),
    # PGN 65257 - Fuel Consumption (Liquid)
    65257: PGNDefinition(
        pgn=65257,
        name="Fuel Consumption (Liquid)",
        acronym="LFC",
        length=8,
        spns=(250, 182),
    ),
    # PGN 65269 - Ambient Conditions
    65269: PGNDefinition(
        pgn=65269,
        name="Ambient Conditions",
        acronym="AMB",
        length=8,
        spns=(108, 170, 171, 172, 79),
    ),
    # PGN 65254 - Time/Date
    65254: PGNDefinition(
        pgn=65254,
        name="Time/Date",
        acronym="TD",
        length=8,
        spns=(959, 960, 961, 962, 963, 964),
    ),
    # PGN 65270 - Inlet/Exhaust Conditions 1
    65270: PGNDefinition(
        pgn=65270,
        name="Inlet/Exhaust Conditions 1",
        acronym="IC1",
        length=8,
        spns=(105, 81, 102, 106, 173),
    ),
    # PGN 65266 - Fuel Economy (Liquid)
    65266: PGNDefinition(
        pgn=65266,
        name="Fuel Economy (Liquid)",
        acronym="LFE1",
        length=8,
        spns=(183, 184, 185, 51),
    ),
    # PGN 65271 - Vehicle Electrical Power 1
    65271: PGNDefinition(
        pgn=65271,
        name="Vehicle Electrical Power 1",
        acronym="VEP1",
        length=8,
        spns=(114, 115, 167, 168),
    ),
    # PGN 65176 - Turbocharger Information 4
    65176: PGNDefinition(
        pgn=65176,
        name="Turbocharger Information 4",
        acronym="TC4",
        length=8,
        spns=(1180, 1181),
    ),
    # PGN 65175 - Turbocharger Information 5
    65175: PGNDefinition(
        pgn=65175,
        name="Turbocharger Information 5",
        acronym="TC5",
        length=8,
        spns=(1184, 1185),
    ),
    # PGN 65110 - Aftertreatment 1 SCR Exhaust Fluid Tank 1
    65110: PGNDefinition(
        pgn=65110,
        name="Aftertreatment 1 SCR Exhaust Fluid Tank 1",
        acronym="AT1T1I",
        length=8,
        spns=(1761, 3031),
    ),
    # PGN 65272 - Transmission Fluids
    65272: PGNDefinition(
        pgn=65272,
        name="Transmission Fluids",
        acronym="TF",
        length=8,
        spns=(124, 126, 127, 177),
    ),
}


# ---------------------------------------------------------------------------
# SPN Database
# ---------------------------------------------------------------------------

SPN_DATABASE: dict[int, SPNDefinition] = {
    # ===== PGN 61444 - EEC1 =====
    899: SPNDefinition(
        spn=899,
        name="Engine Torque Mode",
        pgn=61444,
        start_byte=1,
        start_bit=1,
        bit_length=4,
        resolution=1,
        offset=0,
        unit="",
        min_value=0,
        max_value=15,
    ),
    512: SPNDefinition(
        spn=512,
        name="Driver's Demand Engine Torque",
        pgn=61444,
        start_byte=2,
        start_bit=1,
        bit_length=8,
        resolution=1,
        offset=-125,
        unit="%",
        min_value=-125,
        max_value=125,
    ),
    513: SPNDefinition(
        spn=513,
        name="Actual Engine Torque",
        pgn=61444,
        start_byte=3,
        start_bit=1,
        bit_length=8,
        resolution=1,
        offset=-125,
        unit="%",
        min_value=-125,
        max_value=125,
    ),
    190: SPNDefinition(
        spn=190,
        name="Engine Speed",
        pgn=61444,
        start_byte=4,
        start_bit=1,
        bit_length=16,
        resolution=0.125,
        offset=0,
        unit="rpm",
        min_value=0,
        max_value=8031.875,
    ),
    1483: SPNDefinition(
        spn=1483,
        name="Source Address of Engine Controller",
        pgn=61444,
        start_byte=6,
        start_bit=1,
        bit_length=8,
        resolution=1,
        offset=0,
        unit="",
        min_value=0,
        max_value=255,
    ),
    2432: SPNDefinition(
        spn=2432,
        name="Engine Demand Torque",
        pgn=61444,
        start_byte=8,
        start_bit=1,
        bit_length=8,
        resolution=1,
        offset=-125,
        unit="%",
        min_value=-125,
        max_value=125,
    ),
    # ===== PGN 61443 - EEC2 =====
    29: SPNDefinition(
        spn=29,
        name="Accelerator Pedal Low Idle Switch",
        pgn=61443,
        start_byte=1,
        start_bit=1,
        bit_length=2,
        resolution=1,
        offset=0,
        unit="",
        min_value=0,
        max_value=3,
    ),
    91: SPNDefinition(
        spn=91,
        name="Accelerator Pedal Position 1",
        pgn=61443,
        start_byte=2,
        start_bit=1,
        bit_length=8,
        resolution=0.4,
        offset=0,
        unit="%",
        min_value=0,
        max_value=100,
    ),
    92: SPNDefinition(
        spn=92,
        name="Engine Percent Load At Current Speed",
        pgn=61443,
        start_byte=3,
        start_bit=1,
        bit_length=8,
        resolution=1,
        offset=0,
        unit="%",
        min_value=0,
        max_value=250,
    ),
    974: SPNDefinition(
        spn=974,
        name="Remote Accelerator Pedal Position",
        pgn=61443,
        start_byte=4,
        start_bit=1,
        bit_length=8,
        resolution=0.4,
        offset=0,
        unit="%",
        min_value=0,
        max_value=100,
    ),
    2970: SPNDefinition(
        spn=2970,
        name="Accelerator Pedal Position 2",
        pgn=61443,
        start_byte=6,
        start_bit=1,
        bit_length=8,
        resolution=0.4,
        offset=0,
        unit="%",
        min_value=0,
        max_value=100,
    ),
    # ===== PGN 65262 - ET1 =====
    110: SPNDefinition(
        spn=110,
        name="Engine Coolant Temperature",
        pgn=65262,
        start_byte=1,
        start_bit=1,
        bit_length=8,
        resolution=1,
        offset=-40,
        unit="deg C",
        min_value=-40,
        max_value=210,
    ),
    174: SPNDefinition(
        spn=174,
        name="Fuel Temperature 1",
        pgn=65262,
        start_byte=2,
        start_bit=1,
        bit_length=8,
        resolution=1,
        offset=-40,
        unit="deg C",
        min_value=-40,
        max_value=210,
    ),
    175: SPNDefinition(
        spn=175,
        name="Engine Oil Temperature 1",
        pgn=65262,
        start_byte=3,
        start_bit=1,
        bit_length=16,
        resolution=0.03125,
        offset=-273,
        unit="deg C",
        min_value=-273,
        max_value=1735,
    ),
    176: SPNDefinition(
        spn=176,
        name="Turbo Oil Temperature",
        pgn=65262,
        start_byte=5,
        start_bit=1,
        bit_length=16,
        resolution=0.03125,
        offset=-273,
        unit="deg C",
        min_value=-273,
        max_value=1735,
    ),
    52: SPNDefinition(
        spn=52,
        name="Engine Intercooler Temperature",
        pgn=65262,
        start_byte=7,
        start_bit=1,
        bit_length=8,
        resolution=1,
        offset=-40,
        unit="deg C",
        min_value=-40,
        max_value=210,
    ),
    1134: SPNDefinition(
        spn=1134,
        name="Engine Intercooler Thermostat Opening",
        pgn=65262,
        start_byte=8,
        start_bit=1,
        bit_length=8,
        resolution=0.4,
        offset=0,
        unit="%",
        min_value=0,
        max_value=100,
    ),
    # ===== PGN 65188 - ET2 =====
    1135: SPNDefinition(
        spn=1135,
        name="Engine Oil Temperature 2",
        pgn=65188,
        start_byte=1,
        start_bit=1,
        bit_length=16,
        resolution=0.03125,
        offset=-273,
        unit="deg C",
        min_value=-273,
        max_value=1734.9688,
    ),
    1136: SPNDefinition(
        spn=1136,
        name="Engine ECU Temperature",
        pgn=65188,
        start_byte=3,
        start_bit=1,
        bit_length=16,
        resolution=0.03125,
        offset=-273,
        unit="deg C",
        min_value=-273,
        max_value=1734.9688,
    ),
    411: SPNDefinition(
        spn=411,
        name="Engine Exhaust Gas Recirculation 1 Differential Pressure",
        pgn=65188,
        start_byte=5,
        start_bit=1,
        bit_length=16,
        resolution=1 / 128,
        offset=-250,
        unit="kPa",
        min_value=-250,
        max_value=251.9922,
    ),
    412: SPNDefinition(
        spn=412,
        name="Engine Exhaust Gas Recirculation 1 Temperature",
        pgn=65188,
        start_byte=7,
        start_bit=1,
        bit_length=16,
        resolution=0.03125,
        offset=-273,
        unit="deg C",
        min_value=-273,
        max_value=1734.9688,
    ),
    # ===== PGN 65263 - EFL/P1 =====
    94: SPNDefinition(
        spn=94,
        name="Fuel Delivery Pressure",
        pgn=65263,
        start_byte=1,
        start_bit=1,
        bit_length=8,
        resolution=4,
        offset=0,
        unit="kPa",
        min_value=0,
        max_value=1000,
    ),
    22: SPNDefinition(
        spn=22,
        name="Extended Crankcase Blow-by Pressure",
        pgn=65263,
        start_byte=2,
        start_bit=1,
        bit_length=8,
        resolution=0.05,
        offset=0,
        unit="kPa",
        min_value=0,
        max_value=12.5,
    ),
    98: SPNDefinition(
        spn=98,
        name="Engine Oil Level",
        pgn=65263,
        start_byte=3,
        start_bit=1,
        bit_length=8,
        resolution=0.4,
        offset=0,
        unit="%",
        min_value=0,
        max_value=100,
    ),
    100: SPNDefinition(
        spn=100,
        name="Engine Oil Pressure",
        pgn=65263,
        start_byte=4,
        start_bit=1,
        bit_length=8,
        resolution=4,
        offset=0,
        unit="kPa",
        min_value=0,
        max_value=1000,
    ),
    101: SPNDefinition(
        spn=101,
        name="Crankcase Pressure",
        pgn=65263,
        start_byte=5,
        start_bit=1,
        bit_length=16,
        resolution=1 / 128,
        offset=-250,
        unit="kPa",
        min_value=-250,
        max_value=252,
    ),
    109: SPNDefinition(
        spn=109,
        name="Engine Coolant Pressure",
        pgn=65263,
        start_byte=7,
        start_bit=1,
        bit_length=8,
        resolution=2,
        offset=0,
        unit="kPa",
        min_value=0,
        max_value=500,
    ),
    111: SPNDefinition(
        spn=111,
        name="Engine Coolant Level",
        pgn=65263,
        start_byte=8,
        start_bit=1,
        bit_length=8,
        resolution=0.4,
        offset=0,
        unit="%",
        min_value=0,
        max_value=100,
    ),
    # ===== PGN 65243 - EFL/P2 =====
    164: SPNDefinition(
        spn=164,
        name="Engine Fuel Injection Control Pressure",
        pgn=65243,
        start_byte=1,
        start_bit=1,
        bit_length=16,
        resolution=0.00390625,
        offset=0,
        unit="MPa",
        min_value=0,
        max_value=250.9961,
    ),
    157: SPNDefinition(
        spn=157,
        name="Engine Fuel 1 Injector Metering Rail 1 Pressure",
        pgn=65243,
        start_byte=3,
        start_bit=1,
        bit_length=16,
        resolution=0.00390625,
        offset=0,
        unit="MPa",
        min_value=0,
        max_value=250.9961,
    ),
    156: SPNDefinition(
        spn=156,
        name="Engine Fuel 1 Injector Timing Rail 1 Pressure",
        pgn=65243,
        start_byte=5,
        start_bit=1,
        bit_length=16,
        resolution=0.00390625,
        offset=0,
        unit="MPa",
        min_value=0,
        max_value=250.9961,
    ),
    1349: SPNDefinition(
        spn=1349,
        name="Engine Fuel 1 Injector Metering Rail 2 Pressure",
        pgn=65243,
        start_byte=7,
        start_bit=1,
        bit_length=16,
        resolution=0.00390625,
        offset=0,
        unit="MPa",
        min_value=0,
        max_value=250.9961,
    ),
    # ===== PGN 65265 - CCVS1 =====
    70: SPNDefinition(
        spn=70,
        name="Parking Brake Switch",
        pgn=65265,
        start_byte=1,
        start_bit=1,
        bit_length=2,
        resolution=1,
        offset=0,
        unit="",
        min_value=0,
        max_value=3,
    ),
    84: SPNDefinition(
        spn=84,
        name="Wheel-Based Vehicle Speed",
        pgn=65265,
        start_byte=2,
        start_bit=1,
        bit_length=16,
        resolution=1 / 256,
        offset=0,
        unit="km/h",
        min_value=0,
        max_value=250.996,
    ),
    595: SPNDefinition(
        spn=595,
        name="Cruise Control Active",
        pgn=65265,
        start_byte=4,
        start_bit=1,
        bit_length=2,
        resolution=1,
        offset=0,
        unit="",
        min_value=0,
        max_value=3,
    ),
    596: SPNDefinition(
        spn=596,
        name="Cruise Control Enable Switch",
        pgn=65265,
        start_byte=4,
        start_bit=3,
        bit_length=2,
        resolution=1,
        offset=0,
        unit="",
        min_value=0,
        max_value=3,
    ),
    597: SPNDefinition(
        spn=597,
        name="Brake Switch",
        pgn=65265,
        start_byte=4,
        start_bit=5,
        bit_length=2,
        resolution=1,
        offset=0,
        unit="",
        min_value=0,
        max_value=3,
    ),
    598: SPNDefinition(
        spn=598,
        name="Clutch Switch",
        pgn=65265,
        start_byte=4,
        start_bit=7,
        bit_length=2,
        resolution=1,
        offset=0,
        unit="",
        min_value=0,
        max_value=3,
    ),
    86: SPNDefinition(
        spn=86,
        name="Cruise Control Set Speed",
        pgn=65265,
        start_byte=6,
        start_bit=1,
        bit_length=8,
        resolution=1,
        offset=0,
        unit="km/h",
        min_value=0,
        max_value=250,
    ),
    # ===== PGN 65253 - HOURS =====
    247: SPNDefinition(
        spn=247,
        name="Engine Total Hours of Operation",
        pgn=65253,
        start_byte=1,
        start_bit=1,
        bit_length=32,
        resolution=0.05,
        offset=0,
        unit="h",
        min_value=0,
        max_value=210554060.75,
    ),
    249: SPNDefinition(
        spn=249,
        name="Engine Total Revolutions",
        pgn=65253,
        start_byte=5,
        start_bit=1,
        bit_length=32,
        resolution=1000,
        offset=0,
        unit="rev",
        min_value=0,
        max_value=4211081215000,
    ),
    # ===== PGN 65257 - LFC =====
    250: SPNDefinition(
        spn=250,
        name="Engine Total Fuel Used",
        pgn=65257,
        start_byte=1,
        start_bit=1,
        bit_length=32,
        resolution=0.5,
        offset=0,
        unit="L",
        min_value=0,
        max_value=2105540607.5,
    ),
    182: SPNDefinition(
        spn=182,
        name="Engine Trip Fuel",
        pgn=65257,
        start_byte=5,
        start_bit=1,
        bit_length=32,
        resolution=0.5,
        offset=0,
        unit="L",
        min_value=0,
        max_value=2105540607.5,
    ),
    # ===== PGN 65269 - AMB =====
    108: SPNDefinition(
        spn=108,
        name="Barometric Pressure",
        pgn=65269,
        start_byte=1,
        start_bit=1,
        bit_length=8,
        resolution=0.5,
        offset=0,
        unit="kPa",
        min_value=0,
        max_value=125,
    ),
    170: SPNDefinition(
        spn=170,
        name="Cab Interior Temperature",
        pgn=65269,
        start_byte=2,
        start_bit=1,
        bit_length=16,
        resolution=0.03125,
        offset=-273,
        unit="deg C",
        min_value=-273,
        max_value=1735,
    ),
    171: SPNDefinition(
        spn=171,
        name="Ambient Air Temperature",
        pgn=65269,
        start_byte=4,
        start_bit=1,
        bit_length=16,
        resolution=0.03125,
        offset=-273,
        unit="deg C",
        min_value=-273,
        max_value=1735,
    ),
    172: SPNDefinition(
        spn=172,
        name="Air Inlet Temperature",
        pgn=65269,
        start_byte=6,
        start_bit=1,
        bit_length=8,
        resolution=1,
        offset=-40,
        unit="deg C",
        min_value=-40,
        max_value=210,
    ),
    79: SPNDefinition(
        spn=79,
        name="Road Surface Temperature",
        pgn=65269,
        start_byte=7,
        start_bit=1,
        bit_length=16,
        resolution=0.03125,
        offset=-273,
        unit="deg C",
        min_value=-273,
        max_value=1735,
    ),
    # ===== PGN 65254 - TD =====
    959: SPNDefinition(
        spn=959,
        name="Seconds",
        pgn=65254,
        start_byte=1,
        start_bit=1,
        bit_length=8,
        resolution=0.25,
        offset=0,
        unit="s",
        min_value=0,
        max_value=59.75,
    ),
    960: SPNDefinition(
        spn=960,
        name="Minutes",
        pgn=65254,
        start_byte=2,
        start_bit=1,
        bit_length=8,
        resolution=1,
        offset=0,
        unit="min",
        min_value=0,
        max_value=59,
    ),
    961: SPNDefinition(
        spn=961,
        name="Hours",
        pgn=65254,
        start_byte=3,
        start_bit=1,
        bit_length=8,
        resolution=1,
        offset=0,
        unit="h",
        min_value=0,
        max_value=23,
    ),
    962: SPNDefinition(
        spn=962,
        name="Day",
        pgn=65254,
        start_byte=4,
        start_bit=1,
        bit_length=8,
        resolution=0.25,
        offset=0,
        unit="day",
        min_value=0.25,
        max_value=31.0,
    ),
    963: SPNDefinition(
        spn=963,
        name="Month",
        pgn=65254,
        start_byte=5,
        start_bit=1,
        bit_length=8,
        resolution=1,
        offset=0,
        unit="month",
        min_value=1,
        max_value=12,
    ),
    964: SPNDefinition(
        spn=964,
        name="Year",
        pgn=65254,
        start_byte=6,
        start_bit=1,
        bit_length=8,
        resolution=1,
        offset=1985,
        unit="year",
        min_value=1985,
        max_value=2235,
    ),
    # ===== PGN 65270 - IC1 =====
    105: SPNDefinition(
        spn=105,
        name="Intake Manifold 1 Temperature",
        pgn=65270,
        start_byte=3,
        start_bit=1,
        bit_length=8,
        resolution=1,
        offset=-40,
        unit="deg C",
        min_value=-40,
        max_value=210,
    ),
    81: SPNDefinition(
        spn=81,
        name="Particulate Trap Inlet Pressure",
        pgn=65270,
        start_byte=1,
        start_bit=1,
        bit_length=8,
        resolution=2,
        offset=0,
        unit="kPa",
        min_value=0,
        max_value=500,
    ),
    102: SPNDefinition(
        spn=102,
        name="Boost Pressure",
        pgn=65270,
        start_byte=2,
        start_bit=1,
        bit_length=8,
        resolution=2,
        offset=0,
        unit="kPa",
        min_value=0,
        max_value=500,
    ),
    106: SPNDefinition(
        spn=106,
        name="Air Inlet Pressure",
        pgn=65270,
        start_byte=4,
        start_bit=1,
        bit_length=8,
        resolution=2,
        offset=0,
        unit="kPa",
        min_value=0,
        max_value=500,
    ),
    173: SPNDefinition(
        spn=173,
        name="Exhaust Gas Temperature",
        pgn=65270,
        start_byte=5,
        start_bit=1,
        bit_length=16,
        resolution=0.03125,
        offset=-273,
        unit="deg C",
        min_value=-273,
        max_value=1735,
    ),
    # ===== PGN 65266 - LFE1 =====
    183: SPNDefinition(
        spn=183,
        name="Fuel Rate",
        pgn=65266,
        start_byte=1,
        start_bit=1,
        bit_length=16,
        resolution=0.05,
        offset=0,
        unit="L/h",
        min_value=0,
        max_value=3212.75,
    ),
    184: SPNDefinition(
        spn=184,
        name="Instantaneous Fuel Economy",
        pgn=65266,
        start_byte=3,
        start_bit=1,
        bit_length=16,
        resolution=1 / 512,
        offset=0,
        unit="km/L",
        min_value=0,
        max_value=125.5,
    ),
    185: SPNDefinition(
        spn=185,
        name="Average Fuel Economy",
        pgn=65266,
        start_byte=5,
        start_bit=1,
        bit_length=16,
        resolution=1 / 512,
        offset=0,
        unit="km/L",
        min_value=0,
        max_value=125.5,
    ),
    51: SPNDefinition(
        spn=51,
        name="Throttle Position",
        pgn=65266,
        start_byte=7,
        start_bit=1,
        bit_length=8,
        resolution=0.4,
        offset=0,
        unit="%",
        min_value=0,
        max_value=100,
    ),
    # ===== PGN 65271 - VEP1 =====
    114: SPNDefinition(
        spn=114,
        name="Net Battery Current",
        pgn=65271,
        start_byte=1,
        start_bit=1,
        bit_length=16,
        resolution=1,
        offset=-125,
        unit="A",
        min_value=-125,
        max_value=125,
    ),
    115: SPNDefinition(
        spn=115,
        name="Alternator Current",
        pgn=65271,
        start_byte=3,
        start_bit=1,
        bit_length=16,
        resolution=1,
        offset=-125,
        unit="A",
        min_value=-125,
        max_value=125,
    ),
    167: SPNDefinition(
        spn=167,
        name="Charging System Potential",
        pgn=65271,
        start_byte=5,
        start_bit=1,
        bit_length=16,
        resolution=0.05,
        offset=0,
        unit="V",
        min_value=0,
        max_value=3212.75,
    ),
    168: SPNDefinition(
        spn=168,
        name="Battery Potential",
        pgn=65271,
        start_byte=7,
        start_bit=1,
        bit_length=16,
        resolution=0.05,
        offset=0,
        unit="V",
        min_value=0,
        max_value=3212.75,
    ),
    # ===== PGN 65176 - TC4 =====
    1180: SPNDefinition(
        spn=1180,
        name="Exhaust Temperature Before Turbo 1",
        pgn=65176,
        start_byte=1,
        start_bit=1,
        bit_length=16,
        resolution=0.03125,
        offset=-273,
        unit="deg C",
        min_value=-273,
        max_value=1735,
    ),
    1181: SPNDefinition(
        spn=1181,
        name="Exhaust Temperature Before Turbo 2",
        pgn=65176,
        start_byte=3,
        start_bit=1,
        bit_length=16,
        resolution=0.03125,
        offset=-273,
        unit="deg C",
        min_value=-273,
        max_value=1735,
    ),
    # ===== PGN 65175 - TC5 =====
    1184: SPNDefinition(
        spn=1184,
        name="Exhaust Temperature After Turbo 1",
        pgn=65175,
        start_byte=1,
        start_bit=1,
        bit_length=16,
        resolution=0.03125,
        offset=-273,
        unit="deg C",
        min_value=-273,
        max_value=1735,
    ),
    1185: SPNDefinition(
        spn=1185,
        name="Exhaust Temperature After Turbo 2",
        pgn=65175,
        start_byte=3,
        start_bit=1,
        bit_length=16,
        resolution=0.03125,
        offset=-273,
        unit="deg C",
        min_value=-273,
        max_value=1735,
    ),
    # ===== PGN 65110 - AT1T1I =====
    1761: SPNDefinition(
        spn=1761,
        name="Aftertreatment DEF Tank Level",
        pgn=65110,
        start_byte=1,
        start_bit=1,
        bit_length=8,
        resolution=0.4,
        offset=0,
        unit="%",
        min_value=0,
        max_value=100,
    ),
    3031: SPNDefinition(
        spn=3031,
        name="Aftertreatment DEF Tank Temperature",
        pgn=65110,
        start_byte=2,
        start_bit=1,
        bit_length=8,
        resolution=1,
        offset=-40,
        unit="deg C",
        min_value=-40,
        max_value=210,
    ),
    # ===== PGN 65272 - TF =====
    124: SPNDefinition(
        spn=124,
        name="Transmission Oil Level",
        pgn=65272,
        start_byte=2,
        start_bit=1,
        bit_length=8,
        resolution=0.4,
        offset=0,
        unit="%",
        min_value=0,
        max_value=100,
    ),
    126: SPNDefinition(
        spn=126,
        name="Transmission Filter Differential Pressure",
        pgn=65272,
        start_byte=3,
        start_bit=1,
        bit_length=8,
        resolution=2,
        offset=0,
        unit="kPa",
        min_value=0,
        max_value=500,
    ),
    127: SPNDefinition(
        spn=127,
        name="Transmission Oil Pressure",
        pgn=65272,
        start_byte=4,
        start_bit=1,
        bit_length=8,
        resolution=4,
        offset=0,
        unit="kPa",
        min_value=0,
        max_value=1000,
    ),
    177: SPNDefinition(
        spn=177,
        name="Transmission Oil Temperature",
        pgn=65272,
        start_byte=5,
        start_bit=1,
        bit_length=16,
        resolution=0.03125,
        offset=-273,
        unit="deg C",
        min_value=-273,
        max_value=1735,
    ),
}
